require:
  - rubocop-rspec
  - rubocop-performance

Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 10

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NotToNot:
  EnforcedStyle: to_not

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
